source 'https://rubygems.org'

gemspec
# For debugging in dvm
gem 'pry'
gem 'pry-byebug'
gem 'pry-stack_explorer'
gem 'rake'

# We require chef internally to get the version in
# lib/pedant/request.rb. It's really strange code and it should be
# revisited.
gem 'chef', "16.13.16"

# Cinc patched gems
gem "chef-utils", "= 16.13.16", source: "https://packagecloud.io/cinc-project/stable"
gem "chef-zero", source: "https://packagecloud.io/cinc-project/stable"
gem "inspec-core", "= 4.37.30", source: "https://packagecloud.io/cinc-project/stable"
# Pins for 14.6 release
gem "chef-telemetry", "= 1.0.29"
gem "faraday", "= 1.4.2"
gem "faraday_middleware", "= 1.0.0"
gem "ruby2_keywords", "= 0.0.4"

# For "rake chef_zero_spec"
#gem 'chef-zero', github: 'chef/chef-zero'

# If you want to load debugging tools into the bundle exec sandbox,
# # add these additional dependencies into Gemfile.local
eval(IO.read(__FILE__ + '.local'), binding) if File.exists?(__FILE__ + '.local')

instance_eval(ENV['GEMFILE_MOD']) if ENV['GEMFILE_MOD']
