source 'https://rubygems.org'

gemspec
# For debugging in dvm
gem 'pry'
gem 'pry-byebug'
gem 'pry-stack_explorer'
gem 'rake'

# We require chef internally to get the version in
# lib/pedant/request.rb. It's really strange code and it should be
# revisited.
gem 'chef', "17.9.52",
    source: "https://packagecloud.io/cinc-project/stable"

# For "rake chef_zero_spec"
#gem 'chef-zero', github: 'chef/chef-zero'

# Version lock these to match Gemfile.lock when doing a stable release
if ENV['CHANNEL'] == 'stable' || ENV['CHANNEL'] == 'unstable'
  gem 'aws-partitions', '= 1.556.0'
  gem 'aws-sdk-core', '= 3.126.2'
  gem 'aws-sdk-kms', '= 1.54.0'
  gem 'aws-sdk-s3', '= 1.112.0'
  gem 'aws-sdk-secretsmanager', '= 1.57.0'
  gem 'corefoundation', '= 0.3.13'
  gem 'train-winrm', '= 0.2.12'
end

# If you want to load debugging tools into the bundle exec sandbox,
# # add these additional dependencies into Gemfile.local
eval(IO.read(__FILE__ + '.local'), binding) if File.exists?(__FILE__ + '.local')

instance_eval(ENV['GEMFILE_MOD']) if ENV['GEMFILE_MOD']
