source 'https://rubygems.org'

# Install omnibus software
group :omnibus do
  gem "omnibus", github: ENV.fetch("OMNIBUS_GITHUB_REPO", "chef/omnibus"), branch: ENV.fetch("OMNIBUS_GITHUB_BRANCH", "main")
  gem "omnibus-software", git: ENV.fetch("OMNIBUS_SOFTWARE_GIT_REPO", "https://gitlab.com/cinc-project/upstream/omnibus-software.git"), branch: ENV.fetch("OMNIBUS_SOFTWARE_GIT_BRANCH", "stable/cinc")
  gem 'artifactory'
  gem 'license_scout'
  gem "rest-client", git: "https://github.com/chef/rest-client", branch: "jfm/ucrt_update1"
end

group :test do
  gem 'test-kitchen' # for Test Kitchen testing of the omnibus builds
  gem 'berkshelf', '~> 8.0.22' # depsolving the Test Kitchen suite
  gem 'archive-tar-minitar' # required by berkshelf for packaging
  gem 'chef', '~> 18.8.46'
  gem 'rake'
  gem "rest-client", git: "https://github.com/chef/rest-client", branch: "jfm/ucrt_update1"
end
