source 'https://rubygems.org'

# Install omnibus software
group :omnibus do
  gem 'omnibus', git: 'https://github.com/chef/omnibus'
  gem 'omnibus-software', path: '../../omnibus-software'
  gem 'artifactory'
end

group :test do
  gem 'test-kitchen' # for Test Kitchen testing of the omnibus builds
  gem 'berkshelf' # depsolving the Test Kitchen suite
  gem 'rake'
  gem 'chefspec' # for cookbook chefspec tests
end
