source "https://rubygems.org"
source "https://rubygems.cinc.sh"

gem "sequel", "~> 3.34.1"
gem "pg", "~> 0.16.0"
gem "veil", "0.3.11"
# Version lock these to match Gemfile.lock when doing a stable release
if ENV['CHANNEL'] =~ /stable|unstable|current/
  gem "bcrypt", "= 3.1.16"
end

if ENV['CHANNEL'] =~ /stable|unstable|current/
  gem "chef-utils", "= 16.17.51"
else
  gem "chef-utils", "~> 16.17"
end
