source "https://rubygems.org"

gemspec

# Version lock these to match Gemfile.lock when doing a stable release
if ENV['CHANNEL'] =~ /stable|unstable|current/
  gem "chef", "= 17.10.0", source: "https://packagecloud.io/cinc-project/stable"
else
  gem "chef", "~> 17.10", source: "https://packagecloud.io/cinc-project/stable"
end

gem "toml" # for habitat-land

# Cinc wordmark fixes
gem "chef_backup", source: "https://packagecloud.io/cinc-project/stable"
gem "mixlib-install", source: "https://packagecloud.io/cinc-project/stable"

# Version lock these to match Gemfile.lock when doing a stable release
if ENV['CHANNEL'] =~ /stable|unstable|current/
  gem "aws-partitions", "= 1.571.0"
  gem "chef-vault", "= 4.1.5"
  gem "gyoku", "= 1.3.1"
  gem "inspec-core", "= 4.56.19", source: "https://packagecloud.io/cinc-project/stable"
  gem "ohai", "= 17.9.0"
else
  gem "inspec-core", source: "https://packagecloud.io/cinc-project/stable"
end
